# Stub file for SamplingTree (pybind11 wrapper)

from typing import List, Tuple

class SamplingTree:
    def __init__(self, capacity: int) -> None: ...
    
    def add(self, data: float) -> int: ...
    
    def get_samples(self, batch_size: int) -> Tuple[List[float], List[int]]: ...
    
    def update(self, idxs: List[int], new_values: List[float]) -> None: ...
    
    def update_onestep(self, new_value: float, leafidx: int) -> None: ...
    
    def max_leaf_idx(self) -> int: ...
    
    def max_leaf(self) -> float: ...
    
    def total(self) -> float: ...
    
    def capacity(self) -> int: ...
    
    def real_size(self) -> int: ...
    
    def tree(self) -> List[float]: ...
    
    def __getitem__(self, index: int) -> float: ...

    def show(self) -> None: ...